# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.byte_array import ByteArray  # noqa: F401,E501
import re  # noqa: F401,E501
from swagger_server import util


class Person(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, first_name: str=None, last_name: str=None, username: str=None, date_of_birth: date=None, last_time_online: str=None, avatar_base64_png: ByteArray='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgA……rkJggg=='):  # noqa: E501
        """Person - a model defined in Swagger

        :param first_name: The first_name of this Person.  # noqa: E501
        :type first_name: str
        :param last_name: The last_name of this Person.  # noqa: E501
        :type last_name: str
        :param username: The username of this Person.  # noqa: E501
        :type username: str
        :param date_of_birth: The date_of_birth of this Person.  # noqa: E501
        :type date_of_birth: date
        :param last_time_online: The last_time_online of this Person.  # noqa: E501
        :type last_time_online: str
        :param avatar_base64_png: The avatar_base64_png of this Person.  # noqa: E501
        :type avatar_base64_png: ByteArray
        """
        self.swagger_types = {
            'first_name': str,
            'last_name': str,
            'username': str,
            'date_of_birth': date,
            'last_time_online': str,
            'avatar_base64_png': ByteArray
        }

        self.attribute_map = {
            'first_name': 'firstName',
            'last_name': 'lastName',
            'username': 'username',
            'date_of_birth': 'dateOfBirth',
            'last_time_online': 'lastTimeOnline',
            'avatar_base64_png': 'avatarBase64PNG'
        }

        self._first_name = first_name
        self._last_name = last_name
        self._username = username
        self._date_of_birth = date_of_birth
        self._last_time_online = last_time_online
        self._avatar_base64_png = avatar_base64_png

    @classmethod
    def from_dict(cls, dikt) -> 'Person':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Person of this Person.  # noqa: E501
        :rtype: Person
        """
        return util.deserialize_model(dikt, cls)

    @property
    def first_name(self) -> str:
        """Gets the first_name of this Person.


        :return: The first_name of this Person.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name: str):
        """Sets the first_name of this Person.


        :param first_name: The first_name of this Person.
        :type first_name: str
        """

        self._first_name = first_name

    @property
    def last_name(self) -> str:
        """Gets the last_name of this Person.


        :return: The last_name of this Person.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name: str):
        """Sets the last_name of this Person.


        :param last_name: The last_name of this Person.
        :type last_name: str
        """

        self._last_name = last_name

    @property
    def username(self) -> str:
        """Gets the username of this Person.


        :return: The username of this Person.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this Person.


        :param username: The username of this Person.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def date_of_birth(self) -> date:
        """Gets the date_of_birth of this Person.


        :return: The date_of_birth of this Person.
        :rtype: date
        """
        return self._date_of_birth

    @date_of_birth.setter
    def date_of_birth(self, date_of_birth: date):
        """Sets the date_of_birth of this Person.


        :param date_of_birth: The date_of_birth of this Person.
        :type date_of_birth: date
        """

        self._date_of_birth = date_of_birth

    @property
    def last_time_online(self) -> str:
        """Gets the last_time_online of this Person.


        :return: The last_time_online of this Person.
        :rtype: str
        """
        return self._last_time_online

    @last_time_online.setter
    def last_time_online(self, last_time_online: str):
        """Sets the last_time_online of this Person.


        :param last_time_online: The last_time_online of this Person.
        :type last_time_online: str
        """

        self._last_time_online = last_time_online

    @property
    def avatar_base64_png(self) -> ByteArray:
        """Gets the avatar_base64_png of this Person.


        :return: The avatar_base64_png of this Person.
        :rtype: ByteArray
        """
        return self._avatar_base64_png

    @avatar_base64_png.setter
    def avatar_base64_png(self, avatar_base64_png: ByteArray):
        """Sets the avatar_base64_png of this Person.


        :param avatar_base64_png: The avatar_base64_png of this Person.
        :type avatar_base64_png: ByteArray
        """
        if avatar_base64_png is not None and not re.search(r'^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$', avatar_base64_png):  # noqa: E501
            raise ValueError("Invalid value for `avatar_base64_png`, must be a follow pattern or equal to `/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/`")  # noqa: E501

        self._avatar_base64_png = avatar_base64_png
